### ISSUE TITLE
Teleportation using the Advanced Charged Porter crashes the game

### ISSUE THREAD

**Issue by bothie** [FTBTeam/FTB-Continuum#418]
Modpack Version: 1.3.1, 1.4.1

Issue:

I'm on my Space Station in Orbit around Earth. I try to teleport back to my (chunkloaded) Earth base and (not always but most of the times) the game crashes instantly.

```Time: 8/15/18 7:56 PM
Description: Exception in server tick loop

java.lang.NullPointerException: Exception in server tick loop
        at codechicken.multipart.TickScheduler$WorldTickScheduler._scheduleTick(TickScheduler.scala:44)
        at codechicken.multipart.TickScheduler$WorldTickScheduler$$anonfun$postTick$2.apply(TickScheduler.scala:60)
        at codechicken.multipart.TickScheduler$WorldTickScheduler$$anonfun$postTick$2.apply(TickScheduler.scala:60)
        at scala.collection.immutable.List.foreach(List.scala:383)
        at scala.collection.generic.TraversableForwarder$class.foreach(TraversableForwarder.scala:35)
        at scala.collection.mutable.ListBuffer.foreach(ListBuffer.scala:45)
        at codechicken.multipart.TickScheduler$WorldTickScheduler.postTick(TickScheduler.scala:60)
        at codechicken.lib.world.WorldExtensionManager.postTick(WorldExtensionManager.java:218)
        at codechicken.lib.world.WorldExtensionManager.access$700(WorldExtensionManager.java:20)
        at codechicken.lib.world.WorldExtensionManager$WorldExtensionEventHandler.serverTick(WorldExtensionManager.java:140)
        at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_1627_WorldExtensionEventHandler_serverTick_WorldTickEvent.invoke(.dynamic)
        at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
        at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
        at net.minecraftforge.fml.common.FMLCommonHandler.onPostWorldTick(FMLCommonHandler.java:273)
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:776)
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
        at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:185)
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
        at java.lang.Thread.run(Thread.java:748)
```

Crash log for 1.4.1: [crash-2018-08-15_19.56.50-server.txt](https://github.com/FTBTeam/FTB-Continuum/files/2291194/crash-2018-08-15_19.56.50-server.txt) ([pastebin](https://pastebin.com/D4rCBhc5))

Crash log for 1.3.1 is pretty much the same only the line numbers in the stack trace differ slightly, like TickScheduler.scala:49 instead of TickScheduler.scala:44

Is it Repeatable?: Not 100% of the time, but often enough, if it crashes, it always crashes with a NullPointerException at codechicken.multipart.TickScheduler$WorldTickScheduler._scheduleTick(TickScheduler.scala:44))

**Comment by bothie** [comment]
Just tried to fly back with my rocket - same result.

BTW: Flying to the moon and back worked without a crash.

**Comment by tfox83** [comment]
Known issue with Adv Rock, if there is ever a fix ill get it in ASAP
