### ISSUE TITLE
FTB Continuum Crash through Engineer's Manual

### ISSUE THREAD

**Issue by Timo0o0o0** [FTBTeam/FTB-Continuum#80]
* **Modpack Version**: 1.0.2 FTB Continuum

* **Issue**: If I press the pause key in heavy machines, metal press in the engineers manual and then press the key below, the game will crash

* **Link to Log or Crash File Paste**: 

* **Is it Repeatable?**: yeah

* **Mod/s Affected**: Immersive Engineering

* **Known Fix**:

**Comment by modmuss50** [comment]
Would you be able to get a log please?

**Comment by ghost** [comment]
Error executing task
java.util.concurrent.ExecutionException: java.lang.NullPointerException
	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.util.concurrent.FutureTask.get(FutureTask.java:192)
	at net.minecraft.util.Util.func_181617_a(SourceFile:47)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1086)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:397)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.NullPointerException
	at tonius.simplyjetpacks.item.Jetpack.loadConfig(Jetpack.java:305)
	at tonius.simplyjetpacks.item.Jetpack.loadAllConfigs(Jetpack.java:230)
	at tonius.simplyjetpacks.network.message.MessageConfigSync.handleMessage(MessageConfigSync.java:51)
	at tonius.simplyjetpacks.network.message.MessageConfigSync$1.run(MessageConfigSync.java:42)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at net.minecraft.util.Util.func_181617_a(SourceFile:46)
	... 9 more




And it says something with an error in java 8 v25 but i have already installed java 8 v 171. So that makes no sense?!

**Comment by ByteTemplar** [comment]
Are you using Twitch client? Its not enough to just install newer Java version, you need to activate it in Twitch launcher, so your game is probably still using old version.

https://goo.gl/cCcNu2

Also, post proper logs in pastebin...

**Comment by Svannon** [comment]
Also if you add "-version:1.8+" to the aditional arguments of the minecraft section of the twitch launcher you can force minecraft to use the most recent version of java installed in your system instead of the horibly outdated version that ships with minecraft.  Also this will let you use the newer native launcher.

**Comment by ghost** [comment]
Thx for your nice support. The problem was the java version.......
